#! /bin/sh

bspc monitor HDMI-0 -d 1 2 3 4 5 
bspc monitor HDMI-1 -d 1 2 3 4 5

#Window settings
bspc config border_width		2
bspc config window_gap			10
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true
bspc config top_padding 35
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
#Switch the resize/move mod key which is mod1 in bspwm for some reason? 
bspc config pointer_modifier		mod1
#Border colors
bspc config normal_border_color		"#212121"
bspc config active_border_color		"#212121"
bspc config focused_border_color	"#d3d3d3"
bspc config presel_feedback_color	"#000000"
bspc config urgent_border_color 	"#000000"

#Applications on bspwm session init
picom -b &
xset -dpms s off
nitrogen --restore &
~/.config/polybar/launch.sh &
sxhkd &
