#! /bin/sh
# Workspaces
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 1 2 3

# Window settings
bspc config window_gap			10
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		false
bspc config focus_follows_pointer 	true
bspc config top_padding 		30
bspc config right_padding 		0
bspc config bottom_padding 		0
bspc config left_padding 		0
bspc config border_width 		2

# Border colors
bspc config normal_border_color		"#4a4a4a"
bspc config focused_border_color	"#ffffff"
bspc config active_border_color		"#4a4a4a"
bspc config presel_feedback_color	"#212121"

# Switch the resize/move mod key which is mod1 in bspwm for some reason?
bspc config pointer_modifier		mod1

#Applications on bspwm session init
picom -b &
light-locker &
xset -dpms s off
nitrogen --restore &
~/.config/polybar/polybar.sh &
sxhkd &
/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
